### ISSUE TITLE
Mongoing注册不发送激活邮件

### ISSUE THREAD

**Issue by tjworks** [mongodb-china/community-development#1]
1） Go to mongoing.com 
2)  在右方找到注册链接
3） 输入正确邮件信息注册

Expected:
  收到激活邮件

Actual：
   Nothing

**Comment by xinghuazhao** [comment]
我这里也遇到了同样的情况

**Comment by tjworks** [comment]
@zhangyaoxing 这个问题后来你有跟进吗？

**Comment by zhangyaoxing** [comment]
程序本身有bug，需要DEBUG一下PHP，我尽快进行。

**Comment by zhangyaoxing** [comment]
找回密码：
`/wordpress/wp-login.php` 391行
```
$message = apply_filters( 'retrieve_password_message', $message, $key );
// 应改为
$message = apply_filters( 'retrieve_password_message', $message, $key, $user_login );
```

**Comment by zhangyaoxing** [comment]
WP Mailing Group和SB Welcome Email Editor两个插件都定义了方法`wp_new_user_notification`，全部关闭后功能恢复正常。任意开一个都无法收到Email。可能是两个插件都已过期不能满足再有WP版本正常调用。
两个插件都已禁用，功能恢复正常。
