### ISSUE TITLE
mongoing.com 无法进行注册

### ISSUE THREAD

**Issue by tjworks** [mongodb-china/community-development#24]
症状：

有很多用户汇报无法进行注册，因为收不到邮件

分析：

mandrill邮件账号不稳定

**Comment by zhangyaoxing** [comment]
## 关于发不了邮件
经检查，发不出邮件的具体原因是maildrill的username误写为“MongoDB 中文社区”。考虑到国内外连接的稳定性，决定换成腾讯企业邮箱。
企业邮箱注册后已修改域名CNAME:
smtp.mongoing.com -> smtp.exmail.qq.com
imap.mongoing.com -> imap.exmail.qq.com
**如需要管理员账号或注册其他邮箱请与我联系。**

## 关于修改配置
修改配置后发现WP中的邮箱配置不生效，总是被重置成原来的配置。检查后发现位于以下文件中硬编码了邮箱配置，需要手动修改（以后如有修改也记得改这些地方）：
/data/wpdata/wp-includes/class-phpmailer.php
/data/wpdata/wp-includes/testMailer.php
需要查找这些文件中关于邮箱的配置信息并修改。

## 关于邮箱协议
测试后发现腾讯企业邮箱开启SSL后证书并不合法，最后只能使用25端口非SSL协议配置，经测试发邮件成功。
