### ISSUE TITLE
搭建社区问答系统

### ISSUE THREAD

**Issue by tjworks** [mongodb-china/community-development#8]
基本功能：

- 问题和回答可以upvote 和 downvote
- 支持Markdown
- 微信或者微博集成
- 图片、附件上传功能
- reputation engine
- 中文支持
- 

可选功能
- 邮件组功能
- 实时问答（类聊天）
- 代码格式化
- 支付（悬赏）
- 多租户

**Comment by zhangyaoxing** [comment]
# askbot安装步骤：
## 安装askbot
安装说明：http://askbot.org/doc/install.html
 - 安装EPEL：`sudo rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
 - 安装mysql：
```
> vi /etc/yum.repos.d/MariaDB.repo
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.0/rhel7-amd64/
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1

> yum install MariaDB-server MariaDB-client MariaDB-devel MariaDB-shared
```
 - 各种依赖：`yum install zlib-devel openssl-devel crypto-devel`
 - python全家桶
   - 安装pip： `sudo yum install python-pip`
   - 更新setuptools: `sudo easy_install -U setuptools`
   - python-devel：`sudo yum install python-devel`
   - mysql-python：`pip install mysql-python`
   - 版本命名问题修正：cp `django_threaded_multihost-1.4.post1-py2.7.egg django_threaded_multihost-1.4-1.post1-py2.7.egg`
 - 安装gcc：`sudo yum install gcc`
 - 安装askbot：`sudo pip install askbot`
## 初始化配置
配置说明：http://askbot.org/doc/initial-configuration.html#compile-time-configuration
 - 配置MySQL账户
```
> mysql
CREATE DATABASE [db];
ALTER DATABASE [db] CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER [user]@[host] IDENTIFIED BY '[password]';
GRANT ALL ON [db].* TO [user]@[host];
```
 - 建立安装目录：`mkdir /opt/askbot-django`
 - 初始化askbot：`askbot-setup`期间会询问数据库信息等，使用上一步中填写的内容。
 - 修改SECRET_KEY：`vi settings.py`正常情况下askbot会生成一个KEY，但是如果因为任何原因askbot-setup的时候出错，系统可能不会生成KEY，并且再次运行也不会生成，此时才需要手工填写
 - 一些配置：`vi settings.py`
   - 配置Email：看着配
   - 配置时区：`TIME_ZONE = 'Asia/Shanghai'`
 - 首次运行：
   - `python manage.py collectstatic`
   - `python manage.py syncdb`
   - `python manage.py migrate`

## 运行
```
chmod 755 manage.py
./manage.py runserver 0.0.0.0:80 # DEBUG模式
```

**Comment by zhangyaoxing** [comment]
测试系统架设完成，遗留问题在 #19 中跟踪
